language: node_js

notifications:
  email: false

node_js:
  - "16"

script:
  - npm run docs:build

branches:
  only:
    - main

deploy:
  provider: pages
  local-dir: docs/.vitepress/dist
  skip-cleanup: true
  github-token: $LEMON_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: main
